### ISSUE TITLE
Use popover instead of menu for role dropdown

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#11]
1. Go to library
2. Go to team settings
3. Change someone from developer to user
4. Notice the dialog disappears immediately even if you're not done editing yet. That's because it's a menu but it should be a popover component.

**Comment by jonbell-lot23** [comment]
Hey @souporserious this is a small UI polish issue I've been meaning to figure out. Can you take a look?

**Comment by gideonred** [comment]
This ticket has been moved to [DES-22](https://linear.app/replay/issue/DES-22/use-popover-instead-of-menu-for-role-dropdown)
