### ISSUE TITLE
"Welcome to Replay, <team name>!" can be awkward 

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#12]
![image](https://user-images.githubusercontent.com/9154902/159191799-0292eb87-c548-4807-b22e-c5944e7de1bf.png)

I thought this was a bit awkward. Might be good to re-write the text in a way that doesn't assume the team name is a person name.

**Comment by jaril** [comment]
Wanna take this on? @jonbell-lot23

**Comment by jaril** [comment]
Put this in April for now @jonbell-lot23 let me know if that sounds good!

**Comment by jonbell-lot23** [comment]
I changed the copy to this ->

![image](https://user-images.githubusercontent.com/9154902/164128710-a45de111-2bcd-44ef-b733-ff3e1ae46d5e.png)

That seems like a more appropriate bit of copy for a new team, rather than calling a person by their team name.
