### ISSUE TITLE
Onboarding: make a way to skip the demo

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#17]
We need to add a skip button and make sure the flow is good.

**Comment by jaril** [comment]
@jonbell-lot23 Still a march thing?

**Comment by jonbell-lot23** [comment]
Hey @ceceliacreates you mentioned this a while back and I just got to it as part of an onboarding upgrade -> 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/9154902/164358940-4772d0f3-48ad-4480-b1de-bed640bd9f2e.png">
