### ISSUE TITLE
Print Statements 1.5

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#23]
Suggestions
- [x] Next previous buttons could use a fill which would be more consistent with other buttons
- [x] The summary body could be white which would be a tad lighter
- [x] The edit mode footer should just show the condition button. This will make it more discoverable
- [x] RecordReplay/design#21
- [x] RecordReplay/design#10

[Figma](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11390%3A84953)

### Proposed
![Frame 334](https://user-images.githubusercontent.com/254562/163700615-d95aba0e-4004-4633-bc8f-6c13ca14a176.jpg)

### Current
![Frame 1 (2)](https://user-images.githubusercontent.com/254562/163700620-5a02d9fb-31b2-46a8-b764-b3a6854c7a19.jpg)

**Comment by jonbell-lot23** [comment]
Hey @bvaughn I've got a request!

I fixed a bunch of easy stuff in this ticket, and there's one remaining. We want to remove everything from the bottom row when you're editing a print statement. Here's a visual. Right now it looks like the top one but we want it to be like the bottom one: 

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/9154902/164596680-957f0822-7b6b-4fe3-80a9-7aa9c88b687a.png">

I looked at the code and I wasn't sure the smartest way to say "Hey if you're in edit mode, just don't show all this stuff." The way I had planned to do it feels very sloppy and hacky. Can you do it The Way Brian Would Do It and then show me how you did it?

**Comment by jasonLaster** [comment]
@jonbell-lot23 for fun - how about you open a PR and we can share some feedback on how we'd do it 😄

**Comment by jasonLaster** [comment]
btw here's my quick, didn't run the code guess

```diff
--- a/src/devtools/client/debugger/src/components/SecondaryPanes/Breakpoints/BreakpointNavigation.js
+++ b/src/devtools/client/debugger/src/components/SecondaryPanes/Breakpoints/BreakpointNavigation.js
@@ -54,6 +54,24 @@ function BreakpointNavigation({
     }
   }, [analysisPoints]);

+  if (editing) {
+    <div className="breakpoint-navigation">
+      <div className="flex-grow" />
+      <button
+        className={classnames(
+          "h-5 w-5 rounded-full border p-px pt-0.5",
+          showCondition
+            ? "border-primaryAccent text-primaryAccent"
+            : "border-gray-500 text-gray-500"
+        )}
+        style={{ height: "1.25rem", borderRadius: "100%" }}
+        onClick={() => setShowCondition(!showCondition)}
+      >
+        <MaterialIcon>filter_list</MaterialIcon>
+      </button>
+    </div>;
+  }
+
   return (
     <div className={classnames("breakpoint-navigation", { empty: isEmpty })}>
       {!isEmpty ? (
@@ -65,27 +83,13 @@ function BreakpointNavigation({
         <div className="flex-grow" />
       )}
       <div className="text-center">
-        {editing && (
-          <button
-            className={classnames(
-              "h-5 w-5 rounded-full border p-px pt-0.5",
-              showCondition
-                ? "border-primaryAccent text-primaryAccent"
-                : "border-gray-500 text-gray-500"
-            )}
-            style={{ height: "1.25rem", borderRadius: "100%" }}
-            onClick={() => setShowCondition(!showCondition)}
-          >
-            <MaterialIcon>filter_list</MaterialIcon>
-          </button>
-        )}
-        {!editing && (
+        {
           <PanelStatus
             indexed={indexed}
             executionPoint={lastExecutionPoint}
             analysisPoints={analysisPoints}
           />
-        )}
+        }
       </div>
     </div>
   );
```

**Comment by jonbell-lot23** [comment]
I'm going to start using an acronym to represent a nuanced thought that's going to come up more and more:

I like code challenges but I have a lot of design work to do and that's where I provide the most value to Replay, so the best use of my time with code stuff is to sometimes delegate. Or ....

-> ILCCBIHALODWTDATWIPTMVTRSTBUOMTWCSITSD <-

This one in particular seems doable, because the code snippet above looks fine. But it's lower priority than my design tasks. Best to have eng take it on and I'll learn from it on the periphery.

**Comment by jasonLaster** [comment]
sounds good - happy to run with it

**Comment by bvaughn** [comment]
Haha, just saw that I was assigned and then unassigned this issue while I was asleep 😆  startup life! haha

I'd be happy to do this kind of change (little UI tweaks can be fun!) Feel free to tag me on stuff like this in the future.
