### ISSUE TITLE
500+ hits error should link to Focus Mode, not docs about Focus Mode

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#25]
Right now this happens:

1. 500+ limit
2. User has to know to go to Focus Mode
3. User drags one side in
4. User drags the other side in
5. User clicks away to commit
6. User tries again

This should be replaced with two things:

1. Messaging about Focus Mode (I thought we did this already but maybe not)
2. A single click that applies focus mode to the point you're paused on

**Comment by jasonLaster** [comment]
@jonbell-lot23 here is an example of a hot print statement today.


I like the idea of an button that launches focus mode with a "best guess" window.


I also wonder if it is time to begin discussing some other frontend improvements we could do as well
https://github.com/RecordReplay/design/issues/36

The biggest one that we could do which we can discuss in #36 is adding the ability to progressively evaluate more expressions. How would this work

1. user adds a new print statement with 500+ calls
2. we show 200 messages in the console
3. user wants to see an additional 200 messages, they can either
   3.a click a load more button 
   3.b select a window in the print statement panel and select the next batch they want to load

**Comment by jcmorrow** [comment]
> I like the idea of an button that launches focus mode with a "best guess" window.

Yeah, even in cases where we have thousands of analysis points, we often get back usable results from the backend, and a thing that would be nice is to say "I only ever want to see a window of ten of these in the console, and let's start by using the ten that are closest to my current timestamp". This would actually be really handy for all print statements, even the print statements that are only 200 hits - often the analysis takes a long time because there are so many points to evaluate, when in truth you might not care about 99% of those evaluations.

**Comment by jcmorrow** [comment]
If I had an interface to say "I want to see X neighboring hits, centered around Y time or the Zth hit" I think that would be 🤌

**Comment by jonbell-lot23** [comment]
Here's my short term proposal before we get to Focus Mode 1.1 and #36 :

Right now the page links to docs ->
<img width="557" alt="image" src="https://user-images.githubusercontent.com/9154902/165663472-a4822b8f-2e5a-4ecd-ac45-9d66ea582b03.png">

I think clicking on the words "Focus Mode" should instead trigger our actual Focus Mode. That's a quick win that sets up our broader ideas. Thoughts?

**Comment by jonbell-lot23** [comment]
Marking as design complete and tapping @jcmorrow and @jasonLaster on the shoulder for:

1. Thumbs up
2. Assigning it to someone to make this quick link (not me, I have a big stack of design tasks)
3. Pivoting our attention over to #36

**Comment by jcmorrow** [comment]
Yeah I'm happy to knock this out as a bandaid pre #36
