### ISSUE TITLE
[UX] Design Focus Mode 1.1

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#28]
**Background**

Focus Mode is missing some important stuff. [Here's a loom](https://www.loom.com/share/c84c600cb7684fc7bf65d8c2fd2d07ee) proposing some good improvements.

[Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/?node-id=11491%3A103519)
[Discord thread](https://discord.com/channels/779097926135054346/968316622475513976)

**Details**

* We have a new precision editor in the bottom-right corner
* We default the timeline to a smaller window, rather than requiring it
* We have save, cancel, and discard now
* It's possible to drag the window right and left by clicking in the middle of it
* At first the window follows your cursor, then when you click you can drag the gripper edges as before

**Comment by jasonLaster** [comment]
What do you mean by "A precision selector"

**Comment by jonbell-lot23** [comment]
Right now you can't drag the focus mode window smaller than about 10%, so we show a different view for anything less than 10%. This would address that better.

**Comment by bvaughn** [comment]
I also find that I want to be able to drag the focused region around before "applying" it. That way I don't have to click on the left and right handles and move them both if I have an area I kind of want to scrub around with. (I do this in Cubase a lot.)

**Comment by jonbell-lot23** [comment]
Cc @bvaughn this is making good progress!

By the way, you mentioned the interaction around how the window could move underneath your cursor, and how it could be annoying if it shifted on you. Totally agree -- my thinking is it would track your cursor until a mouse click, at which point it would lock in. From there you'd be able to resize with the edge grippers. So there wouldn't be any mistaken clicks.

**Comment by jonbell-lot23** [comment]
This has been designed (but of course is still open for discussion) so I'm going to close this ticket and we'll track as an eng task rather than a design one from here.
