### ISSUE TITLE
Console error exploration

### ISSUE THREAD

**Issue by jaril** [replayio/design#30]
https://discord.com/channels/779097926135054346/966563248776282133

@jonbell-lot23 I'll let you edit/fill in the details!

**Comment by jonbell-lot23** [comment]
@jaril that link isn't working for me, not sure why. Can you copy/paste the chat here?

**Comment by jaril** [comment]
> @jaril that link isn't working for me, not sure why. Can you copy/paste the chat here?

Doesn't work for me either anymore 😬 Closing this for now since there's no reference (if it's important it'll pop up again!).

Note to self discord links aren't reliable copy paste context if possible!
