### ISSUE TITLE
[exploration] Design "grab last minute" experience (aka flight recorder)

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#33]
We know that in the long run, we want an Xbox/Playstation style "grab last minute" button. This is why we're doing 10 minute recordings and getting other foundational technologies moved into place.

Eventually, we'll have it working and need a design to visualise how it would all work from a user's standpoint. This ticket is to explore that.

**Comment by gideonred** [comment]
This ticket has been moved to [DES-25](https://linear.app/replay/issue/DES-25/[exploration]-design-grab-last-minute-experience-aka-flight-recorder)
