### ISSUE TITLE
Commenting on a network request

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#37]
From @bvaughn 
https://www.loom.com/share/bde37fcb2aef4a52988afb81b34718b3

From @jasonLaster 

- I think the console comment interaction could be useful in the network monitor as well
- I also think we should have a comment button on the request/response panels as well. Discussed it in my 9min goliath of a talk, but adding more contextual comments will be a theme

From @jcmorrow 
* I agree with your instinct Brian, for context the reason it is not there is, I think, because not every request shows a fast-forward/rewind button (unlike console statements), so the "FF or rewind, click again to leave a comment" flow does not work reliably
* but I like the idea of keeping that interaction where it works, and otherwise jumping straight to comment
so if it's "if ff is possible, first click fast-forwards, second click comments" and "if ff is impossible, first click comments" that could be an annoying interaction
* I don't remember actually discussing this the first time, but I suspect that was the thinking

From @jasonLaster 
* yeah - you definitely need selected in those cases.
* I think the experiment I'd run would be:

1. if has a point, show ff/rew in general and comment when paused there
2. if no point, show comment

**Comment by gideonred** [comment]
This ticket has been moved to [DES-28](https://linear.app/replay/issue/DES-28/commenting-on-a-network-request)
