### ISSUE TITLE
[exploration] Explore the next version of comments

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#4]
We've had a lot of ideas around comments over time. Here are a few items to consider:

- [ ] What things aren't possible to add comments to? Should we add them?
- [ ] What if comments were a big text area, like a collaborative document?
- [ ] How can we add more data to comments?
- [ ] Can we be inspired by LookSee? (https://github.com/RecordReplay/design/issues/2)

**Comment by gideonred** [comment]
This ticket has been moved to [DES-21](https://linear.app/replay/issue/DES-21/[exploration]-explore-the-next-version-of-comments)
