### ISSUE TITLE
Progressive (insta) loading

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#42]
We're currently making progress on helping the user understand the replay's current loading state in #40. 

**To recap:**
1. Replay should communicate progress loading regions 
2. Replay should communicate progress buffering the video

This is good and we should move forward here. There is also a larger progressive loading project which we can call insta loading.

**tl;dr**
Brian recently added support for creating a replay session for a partially uploaded recording. He added it to support the cloud-dev flight recorder, but it can also be used to help users view replays as soon as they click save in the Upload screen.

**What changes**
1. Replay would need to communicate the current uploading progress. We actually would know the replay duration, so this is probably fairly reasonable.
2. Replay could also communicate if there is a failure loading a region. Today we kick users to the error modal, but showing the right most portion of the replay timeline after the crash as red might be less jarring to users as they could continue debugging prior to the crash.  

**Prioritization**

We can give this time to bake on the design/product side and implement it when we're ready. My best guess would be June/July. The obvious user benefit is that we could open replays pretty quickly.

**Comment by gideonred** [comment]
This ticket has been moved to [DES-29](https://linear.app/replay/issue/DES-29/progressive-insta-loading)
