### ISSUE TITLE
It should be easier to share a recording

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#43]
@oliverdealb said

"on call with Dyanboard CEO yesterday, he raised a request to be able to switch a setting in his Team so Replays are always shared by default. He mentioned Loom has a nice shortcut (cmd + shit +L) which makes it much faster to share recordings and have all of them available in the library. think this would be a nice feature for Team or Org plan settings?"

Jon says:

I don't understand the exact details yet, but yes. This sounds great and is a real pain point.

**Jon note to self: we also need the ability to select a bunch of items and make them all public at once**

**Comment by oliverdealb** [comment]
Essentially Dynaboard would like “Always share” setting in team or org
settings so all recordings are automatically in the team library and are
viewable. Today, it takes 3 clicks to share each recording and adds
friction to an already friction-filled experience. Let me know if you need
more specifics?

**Comment by jonbell-lot23** [comment]
@oliverdealb I'm starting to look into this now and there may be a difference between how I think the feature works and what others are seeing. cc'ing @jasonLaster and @ryanjduffy for additional insights.

My understanding is that this flow is possible and works:

1. I make a new team
2. I invite people to it
3. Every time I record a replay, it goes into that team's library and every team member has access to it

But that doesn't seem to map to what is being reported here. Jason and Ryan, do you have ideas for what may be wrong here? Oliver, is it possible Dynaboard is doing a strange thing that is causing this?

**Comment by jaril** [comment]
> @oliverdealb I'm starting to look into this now and there may be a difference between how I think the feature works and what others are seeing. cc'ing @jasonLaster and @ryanjduffy for additional insights.
> 
> My understanding is that this flow is possible and works:
> 
> 1. I make a new team
> 2. I invite people to it
> 3. Every time I record a replay, it goes into that team's library and every team member has access to it
> 
> But that doesn't seem to map to what is being reported here. Jason and Ryan, do you have ideas for what may be wrong here? Oliver, is it possible Dynaboard is doing a strange thing that is causing this?

That's correct. When the Dynaboard CEO saves a recording, it should default to Private in the Dynaboard team. Once he hits upload, he shouldn't have to touch any other sharing settings — just copy the link and he's good to go.

@oliverdealb I looked at this briefly and it looks like Alex hasn't recorded anything since 3/16. His default workspace is set correctly as Dynaboard. He might be talking about his experience from a while back and while I can't confirm, it's possible that he wasn't part of the Dynaboard replay team then. 🤷‍♂️ Regardless, his flow should more closely align to what Jon describes here now!

**Comment by jasonLaster** [comment]
Users have asked for comma delimiated lists or pill based lists with autocomplete for adding collaborators

**Comment by jonbell-lot23** [comment]
Note to self: I'm looking into share stuff now. There are a few workstreams, as I see it:

1. Better share dialog that works with our various UX flows (team inbox, upload screen, orgs in library, etc)
2. This ticket, which is more around sharing defaults, bulk sharing, and comma-delimited lists

Stay tuned. Might rename or split out this ticket.

**Comment by jonbell-lot23** [comment]
This ticket is addressed, closing and addressing Jason's comment in this issue:
https://github.com/RecordReplay/design/issues/59

**Comment by oliverdealb** [comment]
Yes that’s the friction. He doesn’t want to have to save every recording,
hit upload and copy the link. He just wants to make a recording and have
all recordings be automatically in his team library and available to anyone
on his team by default. All he has to do is click record. Based on Jon’s
response, it sounds like this is possible.

I copied that flow and shared back with customer. Once customer confirm,
will close this.
