### ISSUE TITLE
Initial docs site

### ISSUE THREAD

**Issue by souporserious** [replayio/design#47]
We should have a NextJS site for displaying documentation about guides, components, theming, figma, etc. I'll be porting over my work from this [case study](https://github.com/souporserious/documenting-systems-in-nextjs) to start and we can eventually move to the official [DocGraph](https://github.com/souporserious/docgraph) library once it's published.

**Comment by gideonred** [comment]
This ticket has been moved to [DES-30](https://linear.app/replay/issue/DES-30/initial-docs-site)
