### ISSUE TITLE
[Explore] Should it be possible to delete a replay from within a replay?

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#53]
Ways you should be able to delete
1. from the replay 
2. from the library 
3. bulk delete in the library

**Comment by jonbell-lot23** [comment]
Design notes:

Numbers 2 and 3 exist already, so the question is around number 1, deleting from inside a replay. To discuss further because I don't want an accidental "[Homer wants lots of horns](https://youtu.be/WPc-VEqBPHI?t=181)" situation

**Comment by jasonLaster** [comment]
@jonbell-lot23 wonder why andarist couldnt find it in the library.

**Comment by jonbell-lot23** [comment]
It happens to the best of us!

The three vertical dots overflow menu on a row is a battle-tested and clear pattern that balances elegance with discoverability. We could bring things forward, but this doesn't meet the bar for something that should exist at a top level. Just like how I wouldn't want these 7 items to have inscrutable icons across the row ->

<img width="211" alt="image" src="https://user-images.githubusercontent.com/9154902/167992613-67d3b2d5-a55b-41e4-98ab-73da2d4beb1e.png">

**Comment by gideonred** [comment]
This ticket has been moved to [DES-32](https://linear.app/replay/issue/DES-32/[explore]-should-it-be-possible-to-delete-a-replay-from-within-a)
