### ISSUE TITLE
Add a forward path (issues, discord, support) to our error screens

### ISSUE THREAD

**Issue by jcmorrow** [replayio/design#54]
Some errors are things that probably don't need further explanation (we turn the server off after 5 minutes of inactivity, you don't have permission, etc.). But lots of things could leave the user feeling a little helpless (e.g. "Something went wrong"). Especially in those open-ended cases, it would be nice to provide the user with an option other than "try again and 🤞 ". Probably some links to discord would be a good starting point, but there could be other stuff too! (I don't know if the design-discussion tag fits here but it seemed right, feel free to retag)!

**Comment by gideonred** [comment]
This ticket has been moved to [DES-33](https://linear.app/replay/issue/DES-33/add-a-forward-path-issues-discord-support-to-our-error-screens)
