### ISSUE TITLE
Design an "exclude node modules" setting to our control-P quick open

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#55]
[From this ticket](https://github.com/RecordReplay/devtools/issues/6811)

We already have this:
![image](https://user-images.githubusercontent.com/9154902/169194322-202a4234-0eaf-46e8-8e10-1011a62f7aab.png)

But it might be nice to do the same thing here, when someone tries to open a file:
![image](https://user-images.githubusercontent.com/9154902/169194359-f9cca4c1-cc52-48f8-8c19-a2611ff7ec10.png)

Jon to design a way to make this work well with our system.

**Comment by jasonLaster** [comment]
We also have the exclude node modules for console logs. We might want to revisit more settings in the settings modal.

**Comment by gideonred** [comment]
This ticket has been moved to [DES-34](https://linear.app/replay/issue/DES-34/design-an-exclude-node-modules-setting-to-our-control-p-quick-open)
