### ISSUE TITLE
Improve rainbow badge icon

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#56]
It seems like we'd be more consistent if the button did not have a border

<img width="247" alt="Screen Shot 2022-05-19 at 9 56 12 PM" src="https://user-images.githubusercontent.com/254562/169453571-bfb6800c-0259-4ec3-889a-b60118245d8b.png">

**Comment by jonbell-lot23** [comment]
Agree, that and a better icon are on my list

**Comment by jonbell-lot23** [comment]
This is a more general item around making a better icon so I changed the issue title. These are four items to address at once:

- [ ] Better background
- [ ] Better visuals
- [ ] Figure out the border
- [ ] Make it play nicely with the filter icon

It's actually best practice for filter to use the fill to represent state (see below). Which means using a border. Which might mean the badge itself might end up with a border too. To be designed.

Here's the standard way it's used:

<img width="32" alt="image" src="https://user-images.githubusercontent.com/9154902/169721266-63cc2375-a8d1-48fa-acae-c8cc4ea7e1f2.png">

<img width="42" alt="image" src="https://user-images.githubusercontent.com/9154902/169721271-d7494f00-4c6e-4499-af39-6c54cc8f7005.png">

**Comment by jonbell-lot23** [comment]
Figma page: https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/?node-id=12395%3A100714

**Comment by jasonLaster** [comment]
Moving this to @souporserious  and intentionally broadening the scope so that the button animates on hover, the picker animates out, and the picker badges pop on hover.
