### ISSUE TITLE
[ux] Share dialogs need comma delimited lists and pills with auto-complete

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#59]
From https://github.com/RecordReplay/design/issues/43 :
"Users have asked for comma delimited lists or pill based lists with autocomplete for adding collaborators"

**Comment by gideonred** [comment]
This ticket has been moved to [DES-35](https://linear.app/replay/issue/DES-35/[ux]-share-dialogs-need-comma-delimited-lists-and-pills-with-auto)
