### ISSUE TITLE
Combine log point and break point UI controls

### ISSUE THREAD

**Issue by bvaughn** [replayio/design#63]
Earlier today I recorded a [Loom describing something that frequently confuses me when using Replay– break points](https://www.loom.com/share/f9dab419cee546c9a48875f7f4611a4a). This lead to a video call with @jaril and @jasonLaster discussing the feature.

Afterward I wrote a rough proposal for how we could combine the log point and break point functionality into a unified control that would (a) be less confusing and (b) give more/better user controls. [Here are the Figma mocks](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=12451%3A95054) and [here is a verbal summary of what I'm proposing on Loom](https://www.loom.com/share/e3952c51421d447e8ff775ec41a604fb).

Here is a visual summary:
![Screen Shot 2022-05-24 at 5 43 01 PM](https://user-images.githubusercontent.com/29597/170137349-79ee7c78-55b9-4685-937a-c8048e1888c2.png)

My sense is that everyone I've spoken to about this idea (also including @markerikson, @jonbell-lot23, and @ryanjduffy) are generally supportive. This issue is a placeholder then for any additional discussion and for us to prioritize when to work on this.

**Comment by jonbell-lot23** [comment]
Jason Loom: https://www.loom.com/share/adf4513ff58a4eb3a9aaf8dfc0f62f47

Jason notes for Jon:
- tooltips (perhaps unfurl, or a nicer react styled tooltip)
- representing state in the summary

Discord discussion: https://discord.com/channels/779097926135054346/978716085018837092

**Comment by bvaughn** [comment]
Some thoughts on Jason's Loom:
1. I agree that the eye doesn't work well for log point toggle. (It was just a placeholder in the initial pitch.)
2. I really like bringing the break behavior badge to right beside of the timeline!

I propose that if we have such a simple break toggle, we don't really even need separate _disable_ break button. You could just toggle break functionality back off.

Then at that point, we only need a toggle for console logging, which we could probably just move up a bit, to the right of the log message. Maybe something like this? (although I'm still using the eye, just ignore that for now)

![Screen Shot 2022-05-25 at 8 26 13 AM](https://user-images.githubusercontent.com/29597/170263645-b264d8af-084d-4942-bcb6-7fca4a65261c.png)

**Comment by gideonred** [comment]
This ticket has been moved to [DES-37](https://linear.app/replay/issue/DES-37/combine-log-point-and-break-point-ui-controls)
