### ISSUE TITLE
[explore] Look into buffering tooltips for Global Loader 1.6

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/design#66]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/9154902/170211209-bcb9a12e-bb88-4c61-8dde-30a696575bde.png">

In production we use a little tooltip to show the timestamp. I'm not seeing a big benefit to swapping out the timestamp to say "buffering" or "processing." To discuss more.

**Comment by jonbell-lot23** [comment]
@jcmorrow @bvaughn on Monday we talked about hovering over the timeline to get more data. We talked about showing buffering versus processing, as well as hovering over the play button.

I think I'm missing something here, because a) I'm not seeing the benefit b) we're already showing a tooltip on the timeline, so even if we wanted to say "buffering" we'd have to deal with the timestamp. To discuss.

**Comment by bvaughn** [comment]
I think the text "buffering" was just meant to aid users who might not know what the different colors mean (and might expect clicking there to immediately start playback). We could still show the timestamp (e.g. "0.21 (buffering)"

**Comment by jonbell-lot23** [comment]
I hear that. But yeah, I think "0:21 (buffering)" feels a bit heavy-handed. I'd propose doing all the other items and if we later think this is necessary we can consider it then.

**Comment by jonbell-lot23** [comment]
(Closing this for GitHub iteration tracking reasons. Still happy to discuss of course, just cleaning up sprint board and we're at a pretty good design POV even if we're not fully aligned yet)
